-- MySQL Script generated by MySQL Workbench
-- qua 30 ago 2023 14:45:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema streamingDadosSLQ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema streamingDadosSLQ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `streamingDadosSLQ` ;
USE `streamingDadosSLQ` ;

-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `senha` VARCHAR(45) NULL,
  `moderador` TINYINT NULL,
  `genero` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `premium` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`reproducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`reproducao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `nome` VARCHAR(45) NULL,
  `tempo` DATETIME NULL,
  `genero` VARCHAR(45) NULL,
  `avaliacao` INT(5) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_reproducao_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_reproducao_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `streamingDadosSLQ`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`postagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(100) NULL,
  `registro` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_postagem_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_postagem_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `streamingDadosSLQ`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`curtida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`curtida` (
  `id_postagem` INT NOT NULL,
  `id_usuario` INT NULL,
  `postagem_id` INT NOT NULL,
  PRIMARY KEY (`id_postagem`, `postagem_id`),
  INDEX `fk_curtida_postagem1_idx` (`postagem_id` ASC),
  CONSTRAINT `fk_curtida_postagem1`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `streamingDadosSLQ`.`postagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`comentario` (
  `id_postagem` INT NOT NULL,
  `id_usuario` INT NULL,
  `conteudo` VARCHAR(280) NULL,
  `postagem_id` INT NOT NULL,
  PRIMARY KEY (`id_postagem`, `postagem_id`),
  INDEX `fk_comentario_postagem1_idx` (`postagem_id` ASC),
  CONSTRAINT `fk_comentario_postagem1`
    FOREIGN KEY (`postagem_id`)
    REFERENCES `streamingDadosSLQ`.`postagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`pesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`pesquisa` (
  `id_reproducao` INT NOT NULL,
  `nome_reproducao` VARCHAR(45) NULL,
  `reproducao_id` INT NOT NULL,
  `reproducao_usuario_id1` INT NOT NULL,
  PRIMARY KEY (`id_reproducao`, `reproducao_id`, `reproducao_usuario_id1`),
  INDEX `fk_pesquisa_reproducao1_idx` (`reproducao_id` ASC, `reproducao_usuario_id1` ASC),
  CONSTRAINT `fk_pesquisa_reproducao1`
    FOREIGN KEY (`reproducao_id` , `reproducao_usuario_id1`)
    REFERENCES `streamingDadosSLQ`.`reproducao` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`historico` (
  `id_reproducao` INT NOT NULL,
  `nome_reproducao` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  `registro` DATETIME NULL,
  PRIMARY KEY (`id_reproducao`, `usuario_id`),
  INDEX `fk_historico_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `streamingDadosSLQ`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `streamingDadosSLQ`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streamingDadosSLQ`.`pagamento` (
  `id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `usuario_premium` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_pagamento_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_pagamento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `streamingDadosSLQ`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
